title:             The Sun Trip 2018
email:             auguste.colle@kuleuven.be
description:       A blog about our participation in the Sun Trip 2018
author:            Auguste & Camille
baseurl:           "/Suntrip"
url:               ""

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
